### ISSUE TITLE
模组计划列表 / TODO List

### ISSUE THREAD

**Issue by nitu2003** [DeepStoneCrypt/RefinedStorageEnlightened#1]
### General / Coding

- [ ] improve the compatition
- [ ] optimize the code of TileBotaniaCraftingTable

### Features

- [ ] add the recipe for BotaniaCraftingTable
- [ ] add the texture for BotaniaCraftingTable
